### ISSUE TITLE
SM: stats result of fs.stat(Sync) is a function instead of an object

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#242]
I've encountered this while testing `sendFile` of npm `express` module. It seems, that `express` before sending a file calls `fs.stat(path, function(err, stat) {})` and checks if `typeof stat` equals to "object". For SM this fails, since `typeof stat` is "function".

```js
var fs = require('fs');

// async method
fs.stat(__filename, function (err, stat) {
  console.log("ASYNC typeof stat:", typeof stat);
});

// sync method
var stat = fs.statSync(__filename);
console.log("SYNC typeof stat:", typeof stat);
```

SM output:
> SYNC typeof stat: **function**
ASYNC typeof stat: **function**

V8 output:
> SYNC typeof stat: **object**
ASYNC typeof stat: **object**

However `stat instanceof fs.Stats` is still `true` and this have fooled our test cases. That's why the issue did not occur earlier.

**Comment by obastemur** [comment]
Can we update the same test case with this extra ?

**Comment by obastemur** [comment]
This is one another non-standard behavior from V8.. Stat is literally a function but v8 unfortunately shows it type as an 'object'. Anyway there is a workaround on this.

**Comment by obastemur** [comment]
Actually 'Stats' is a function not an Object. V8 shows 'object' for native function instances. Reported this on etag's repo: https://github.com/jshttp/etag/issues/10

**Comment by dougwilson** [comment]
If anyone can help test a fix, please comment over in the linked `etag` issue.

**Comment by ktrzeciaknubisa** [comment]
Well, after the f72d3d3ec9e392a5a0b70297e6a78f951ad3beee fix, few things got broke, also for V8. I have prepared separated test case for issues related to fs stat matter:

```bash
$ ./jx test/run.js -file test/jxcore/test-fs-stats.js
```
For SM stat.toString() fails:

> SM - failed for fs.statSync(): : TypeError: Function.prototype.toString called on incompatible object
SM - failed for fs.lstatSync(): : TypeError: Function.prototype.toString called on incompatible object
SM - failed for fs.fstatSync(): : TypeError: Function.prototype.toString called on incompatible object
SM - failed for fs.stat(): : TypeError: Function.prototype.toString called on incompatible object
SM - failed for fs.lstat(): : TypeError: Function.prototype.toString called on incompatible object
SM - failed for fs.fstat(): : TypeError: Function.prototype.toString called on incompatible object

V8 sync methods are ok, while async got broke:

> V8 - failed for fs.stat(): typeof stat is not 'object'
V8 - failed for fs.stat(): stat is not instance of fs.Stats
V8 - failed for fs.lstat(): typeof stat is not 'object'
V8 - failed for fs.lstat(): stat is not instance of fs.Stats
V8 - failed for fs.fstat(): typeof stat is not 'object'
V8 - failed for fs.fstat(): stat is not instance of fs.Stats

For the old good JXcore 0.2.3.7 all tests are green.

**Comment by obastemur** [comment]
Ok lets make this a simple test case

**Comment by obastemur** [comment]
fixed.

**Comment by ktrzeciaknubisa** [comment]
It looks like the problem persists, but this time only while reading **assets embedded** in jx/native packages (reading files from filesystem works ok).

```bash
$ ./jx test/run.js -file test/jxcore/test-fs-stats-assets.js -p
SM - failed for fs.stat(): typeof stat is not 'object'
SM - failed for fs.statSync(): typeof stat is not 'object'
SM - failed for fs.lstat(): typeof stat is not 'object'
SM - failed for fs.lstatSync(): typeof stat is not 'object'
```

**Comment by ktrzeciaknubisa** [comment]
Solved with ea249dfd0dca18edb83d71487cb4a11a468d8bdc and 34a8a3c5be8230e090ebc109729a51c37cec7154.
